### ISSUE TITLE
Not working in ubuntu 18.04

### ISSUE THREAD

**Issue by devarthurribeiro** [PhonePresenter/PhonePresenter#1]
The commands keys not run in ubuntu 18.4. 

I'm fork the repo to add support to socket and robot.js and fix the bugs.

Beyond add tests. 

what do you think ?

**Comment by chromatical** [comment]
This is likely due to Ubuntu switching to Wayland in 17.10 (xdotool doesn't work under Wayland).  Unfortunately, RobotJS [doesn't appear to work either](https://github.com/octalmage/robotjs/issues/333), so I think we may just have to stick with X.org support until a good solution shows up.

Websockets and tests are welcome.  Thank you for your help!

**Comment by devarthurribeiro** [comment]
I'm using RobotJS on Ubuntu 18.04. I don't have problems.

**Comment by chromatical** [comment]
Okay, that's good to know.

**Comment by chromatical** [comment]
@devarthurribeiro I just published a new release that uses RobotJS, so PhonePresenter should work with Ubuntu 18.04 now.  I'll close this issue, but let me know if it still doesn't work and I'll reopen it.  Thank you!
